import { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    absolute: '',
    default: 'Next.js Tutorial - Quan',
    template: "%s | Quan's Website",
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            backgroundColor: 'lightblue',
            padding: '1rem',
          }}
        >
          <p className="text-white">Header</p>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: 'ghostwhite',
            padding: '1rem',
          }}
        >
          <p> Footer</p>
        </footer>
      </body>
    </html>
  );
}
